-- SEC-AUTH-002: one-time MFA recovery codes and database-enforced recovery lock.
--
-- Raw recovery codes never enter Postgres. The mfa-recovery Edge Function
-- stores only HMAC-SHA256 values produced with a server-only pepper. Privileged
-- functions are service-role-only and use fixed search paths.

create table if not exists public.mfa_recovery_state (
    user_id                       uuid primary key references auth.users(id) on delete cascade,
    recovery_required            boolean not null default false,
    current_generation           uuid,
    codes_generated_at           timestamptz,
    recovery_started_at          timestamptz,
    recovery_completed_at        timestamptz,
    failed_attempts               smallint not null default 0 check (failed_attempts between 0 and 5),
    attempt_window_started_at     timestamptz,
    locked_until                  timestamptz,
    generation_notice_sent_at    timestamptz,
    recovery_notice_sent_at      timestamptz,
    completion_notice_sent_at    timestamptz,
    updated_at                    timestamptz not null default now()
);

create table if not exists public.mfa_recovery_codes (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    generation  uuid not null,
    code_hash   text not null check (code_hash ~ '^[0-9a-f]{64}$'),
    created_at  timestamptz not null default now(),
    unique (user_id, code_hash)
);

create index if not exists mfa_recovery_codes_user_generation_idx
    on public.mfa_recovery_codes(user_id, generation);

alter table public.mfa_recovery_state enable row level security;
alter table public.mfa_recovery_codes enable row level security;

revoke all on table public.mfa_recovery_state from public, anon, authenticated;
revoke all on table public.mfa_recovery_codes from public, anon, authenticated;
grant select on table public.mfa_recovery_state to authenticated;
grant all on table public.mfa_recovery_state to service_role;
grant all on table public.mfa_recovery_codes to service_role;
grant usage, select on sequence public.mfa_recovery_codes_id_seq to service_role;

drop policy if exists "own MFA recovery state - select" on public.mfa_recovery_state;
create policy "own MFA recovery state - select"
    on public.mfa_recovery_state
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

-- No browser policy exists for mfa_recovery_codes. The table is deliberately
-- inaccessible even to its owner because code hashes are server-only material.

create or replace function public.replace_mfa_recovery_codes(
    p_user_id uuid,
    p_generation uuid,
    p_code_hashes text[]
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if p_user_id is null
       or p_generation is null
       or p_code_hashes is null
       or cardinality(p_code_hashes) <> 10
       or exists (
            select 1
            from unnest(p_code_hashes) as code_hash
            where code_hash !~ '^[0-9a-f]{64}$'
       ) then
        raise exception 'invalid recovery-code set';
    end if;

    delete from public.mfa_recovery_codes
    where user_id = p_user_id;

    insert into public.mfa_recovery_codes (user_id, generation, code_hash)
    select p_user_id, p_generation, code_hash
    from unnest(p_code_hashes) as code_hash;

    insert into public.mfa_recovery_state (
        user_id,
        recovery_required,
        current_generation,
        codes_generated_at,
        recovery_started_at,
        recovery_completed_at,
        failed_attempts,
        attempt_window_started_at,
        locked_until,
        generation_notice_sent_at,
        recovery_notice_sent_at,
        completion_notice_sent_at,
        updated_at
    ) values (
        p_user_id,
        false,
        p_generation,
        now(),
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        now()
    )
    on conflict (user_id) do update set
        recovery_required = false,
        current_generation = excluded.current_generation,
        codes_generated_at = excluded.codes_generated_at,
        recovery_started_at = null,
        recovery_completed_at = null,
        failed_attempts = 0,
        attempt_window_started_at = null,
        locked_until = null,
        generation_notice_sent_at = null,
        recovery_notice_sent_at = null,
        completion_notice_sent_at = null,
        updated_at = now();
end;
$$;

create or replace function public.claim_mfa_recovery_code(
    p_user_id uuid,
    p_code_hash text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_state public.mfa_recovery_state%rowtype;
    v_code_id bigint;
    v_attempts smallint;
begin
    if p_user_id is null or p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$' then
        return 'invalid';
    end if;

    insert into public.mfa_recovery_state (user_id)
    values (p_user_id)
    on conflict (user_id) do nothing;

    select * into v_state
    from public.mfa_recovery_state
    where user_id = p_user_id
    for update;

    if v_state.recovery_required then
        return 'resume';
    end if;

    if v_state.locked_until is not null and v_state.locked_until > now() then
        return 'locked';
    end if;

    if v_state.attempt_window_started_at is null
       or v_state.attempt_window_started_at < now() - interval '15 minutes' then
        update public.mfa_recovery_state set
            failed_attempts = 0,
            attempt_window_started_at = now(),
            locked_until = null,
            updated_at = now()
        where user_id = p_user_id;
        v_state.failed_attempts := 0;
    end if;

    select id into v_code_id
    from public.mfa_recovery_codes
    where user_id = p_user_id
      and generation = v_state.current_generation
      and code_hash = p_code_hash
    for update;

    if v_code_id is null then
        v_attempts := least(v_state.failed_attempts + 1, 5);
        update public.mfa_recovery_state set
            failed_attempts = v_attempts,
            attempt_window_started_at = coalesce(attempt_window_started_at, now()),
            locked_until = case when v_attempts >= 5 then now() + interval '15 minutes' else null end,
            updated_at = now()
        where user_id = p_user_id;
        return case when v_attempts >= 5 then 'locked' else 'invalid' end;
    end if;

    -- Consuming one code invalidates the complete set. A newly recovered user
    -- can generate a replacement set after re-enrolling MFA at AAL2.
    delete from public.mfa_recovery_codes
    where user_id = p_user_id;

    update public.mfa_recovery_state set
        recovery_required = true,
        current_generation = null,
        recovery_started_at = now(),
        recovery_completed_at = null,
        failed_attempts = 0,
        attempt_window_started_at = null,
        locked_until = null,
        recovery_notice_sent_at = null,
        completion_notice_sent_at = null,
        updated_at = now()
    where user_id = p_user_id;

    return 'accepted';
end;
$$;

create or replace function public.revoke_mfa_recovery_codes(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    delete from public.mfa_recovery_codes
    where user_id = p_user_id;

    update public.mfa_recovery_state set
        current_generation = null,
        codes_generated_at = null,
        generation_notice_sent_at = null,
        failed_attempts = 0,
        attempt_window_started_at = null,
        locked_until = null,
        updated_at = now()
    where user_id = p_user_id
      and recovery_required = false;
end;
$$;

create or replace function public.complete_mfa_recovery(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    delete from public.mfa_recovery_codes
    where user_id = p_user_id;

    update public.mfa_recovery_state set
        recovery_required = false,
        current_generation = null,
        recovery_completed_at = now(),
        failed_attempts = 0,
        attempt_window_started_at = null,
        locked_until = null,
        updated_at = now()
    where user_id = p_user_id
      and recovery_required = true;
end;
$$;

revoke all on function public.replace_mfa_recovery_codes(uuid, uuid, text[]) from public, anon, authenticated;
revoke all on function public.claim_mfa_recovery_code(uuid, text) from public, anon, authenticated;
revoke all on function public.revoke_mfa_recovery_codes(uuid) from public, anon, authenticated;
revoke all on function public.complete_mfa_recovery(uuid) from public, anon, authenticated;
grant execute on function public.replace_mfa_recovery_codes(uuid, uuid, text[]) to service_role;
grant execute on function public.claim_mfa_recovery_code(uuid, text) to service_role;
grant execute on function public.revoke_mfa_recovery_codes(uuid) to service_role;
grant execute on function public.complete_mfa_recovery(uuid) to service_role;

-- Every tenant-data table receives two restrictive policies:
--  * opted-in MFA users need an AAL2 JWT even when calling the Data API directly;
--  * a recovered account cannot read or mutate business data until a new factor
--    is verified and the recovery lock is completed.
do $$
declare
    tenant_table text;
begin
    foreach tenant_table in array array[
        'company_settings',
        'customers',
        'saved_items',
        'invoices',
        'recurring_templates',
        'audit_events'
    ] loop
        execute format('drop policy if exists %I on public.%I',
            'MFA assurance required for opted-in accounts', tenant_table);
        execute format($policy$
            create policy %I on public.%I
            as restrictive
            for all
            to authenticated
            using (
                array[(select auth.jwt()->>'aal')] <@ (
                    select case
                        when count(id) > 0 then array['aal2']
                        else array['aal1', 'aal2']
                    end
                    from auth.mfa_factors
                    where user_id = (select auth.uid())
                      and status = 'verified'
                )
            )
            with check (
                array[(select auth.jwt()->>'aal')] <@ (
                    select case
                        when count(id) > 0 then array['aal2']
                        else array['aal1', 'aal2']
                    end
                    from auth.mfa_factors
                    where user_id = (select auth.uid())
                      and status = 'verified'
                )
            )
        $policy$, 'MFA assurance required for opted-in accounts', tenant_table);

        execute format('drop policy if exists %I on public.%I',
            'MFA recovery must be completed', tenant_table);
        execute format($policy$
            create policy %I on public.%I
            as restrictive
            for all
            to authenticated
            using (
                not exists (
                    select 1
                    from public.mfa_recovery_state
                    where user_id = (select auth.uid())
                      and recovery_required = true
                )
            )
            with check (
                not exists (
                    select 1
                    from public.mfa_recovery_state
                    where user_id = (select auth.uid())
                      and recovery_required = true
                )
            )
        $policy$, 'MFA recovery must be completed', tenant_table);
    end loop;
end;
$$;

comment on table public.mfa_recovery_state is
    'Minimal state for one-time MFA recovery and forced TOTP re-enrolment.';
comment on table public.mfa_recovery_codes is
    'Server-only HMAC-SHA256 recovery-code values; raw codes are never stored.';
